{application,pigeon,
             [{modules,['Elixir.Pigeon','Elixir.Pigeon.Application',
                        'Elixir.Pigeon.CLI','Elixir.Pigeon.Cluster.Manager',
                        'Elixir.Pigeon.Communication.Hub',
                        'Elixir.Pigeon.Config',
                        'Elixir.Pigeon.Infrastructure.EC2Manager',
                        'Elixir.Pigeon.Jobs.JobManager',
                        'Elixir.Pigeon.Validators.GExpressionValidator',
                        'Elixir.Pigeon.Work.Processor',
                        'Elixir.Pigeon.Work.Validator']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,crypto,ssl,inets,
                             jason,req,finch,ex_aws,ex_aws_ec2,hackney,
                             optimus]},
              {description,"Generic Distributed Work Processing Framework"},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.Pigeon.Application',[]}}]}.
